<?php
$defaultSuspects = [
  ["name" => 'None',
  "height" => 'None',
  "alibi" => 'None',
  "nationality" => 'None',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  "id" => 0,
  ],
  ["name" => 'None',
  "height" => 'None',
  "alibi" => 'None',
  "nationality" => 'None',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  "id" => 1,
  ],
  ["name" => 'None',
  "height" => 'None',
  "alibi" => 'None',
  "nationality" => 'None',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  "id" => 2,
  ],
  ["name" => 'None',
  "height" => 'None',
  "alibi" => 'None',
  "nationality" => 'None',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  "id" => 3,
  ],
  ["name" => 'None',
  "height" => 'None',
  "alibi" => 'None',
  "nationality" => 'None',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  "id" => 4,
  ],
  ["name" => 'None',
  "height" => 'None',
  "alibi" => 'None',
  "nationality" => 'None',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  "id" => 5,
  ],
  ["name" => 'None',
  "height" => 'None',
  "alibi" => 'None',
  "nationality" => 'None',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  "id" => 6,
  ]
];
?>