<?php
$defaultSuspects = [
  ["name" => 'Unknown',
  "height" => 'Unknow',
  "alibi" => 'Unknown',
  "nationality" => 'Unknown',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  "id" => 0,
  "age" => "Unknown"
  ],
  ["name" => 'Unknown',
  "height" => 'Unknown',
  "alibi" => 'Unknown',
  "nationality" => 'Unknown',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  "id" => 1,
  "age" => "Unknown"
  ],
  ["name" => 'Unknown',
  "height" => 'Unknown',
  "alibi" => 'Unknown',
  "nationality" => 'Unknown',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  "id" => 2,
  "age" => "Unknown"
  ],
  ["name" => 'Unknown',
  "height" => 'Unknown',
  "alibi" => 'Unknown',
  "nationality" => 'Unknown',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  "id" => 3,
  "age" => "Unknown"
  ],
  ["name" => 'Unknown',
  "height" => 'Unknown',
  "alibi" => 'Unknown',
  "nationality" => 'Unknown',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  "id" => 4,
  "age" => "Unknown"
  ],
  ["name" => 'Unknown',
  "height" => 'Unknown',
  "alibi" => 'Unknown',
  "nationality" => 'Unknown',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  "id" => 5,
  "age" => "Unknown"
  ],
  ["name" => 'Unknown',
  "height" => 'Unknown',
  "alibi" => 'Unknown',
  "nationality" => 'Unknown',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  "id" => 6,
  "age" => "Unknown"
  ],
  ["name" => 'Unknown',
  "height" => 'Unknown',
  "alibi" => 'Unknown',
  "nationality" => 'Unknown',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  "id" => 7,
  "age" => "Unknown"
  ]
];
?>