<?php
$defaultSuspects = [
  ["name" => 'None',
  "height" => 'None',
  "alibi" => 'None',
  "nationality" => 'None',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  ],
  ["name" => 'None',
  "height" => 'None',
  "alibi" => 'None',
  "nationality" => 'None',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  ],
  ["name" => 'None',
  "height" => 'None',
  "alibi" => 'None',
  "nationality" => 'None',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  ],
  ["name" => 'None',
  "height" => 'None',
  "alibi" => 'None',
  "nationality" => 'None',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  ],
  ["name" => 'None',
  "height" => 'None',
  "alibi" => 'None',
  "nationality" => 'None',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  ],
  ["name" => 'None',
  "height" => 'None',
  "alibi" => 'None',
  "nationality" => 'None',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  ],
  ["name" => 'None',
  "height" => 'None',
  "alibi" => 'None',
  "nationality" => 'None',
  "notes" => '',
  "image" => '../images/',
  "isStillSuspect" => true,
  ]
];
?>